"""
proof_loop.py — did the model's forecasts actually come true? (CLI)

Thin command-line wrapper over the canonical receipts engine in
stage8_output/track_record.py. Runs the out-of-time backtest and writes a
one-page scorecard a prospect can read. The same logic powers the
"Track Record" sheet in the weekly Excel report.

Usage:
    python -X utf8 scripts/diagnostics/proof_loop.py --weeks 8

Outputs (output/runs/_proof_loop/):
    PROOF_LOOP_REPORT.md      one-page out-of-time validation scorecard
    discount_move_validation.csv   predicted vs actual volume change by move type
"""
import os
import sys
import argparse
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, ROOT)

import v4_config as cfg
from stage1_ingestion.ingest import ingest_all_sales, load_event_calendar, load_master_costs
from stage2_preparation.prepare import prepare_fact_table
from stage3_features.features import engineer_features
from stage8_output.track_record import run_backtest


def _n(x, nd, suf=""):
    """Format a metric that may be None (degenerate window) as N/A."""
    return "N/A" if x is None else f"{x:.{nd}f}{suf}"


def _write_report(bt, out_dir, weeks):
    md = []
    md.append("# Proof Loop — did the forecasts come true?\n")
    if not bt.get("available"):
        md.append(f"\n_Backtest unavailable: {bt.get('reason', 'unknown')}._\n")
        return md
    md.append(f"> Out-of-time validation. The model was trained on data up to "
              f"**{bt['cutoff']}** and then asked to predict the **{weeks} weeks after** "
              f"(ending {bt['max_date']}) — a window it never saw. Generated by "
              f"`scripts/diagnostics/proof_loop.py`.\n")

    md.append("\n## 1. Forward-window forecast accuracy\n")
    md.append("\n| Grain | R² | Avg error (MAPE) |")
    md.append("|---|---:|---:|")
    md.append(f"| Daily | {_n(bt['daily_r2'],3)} | {_n(bt['daily_mape'],1,'%')} |")
    if bt.get("bin_r2") is not None:
        md.append(f"| 3ppt discount bin | {_n(bt['bin_r2'],3)} | {_n(bt['bin_mape'],1,'%')} |")
    md.append(f"\n*{bt['n_forward_days']:,} forward days across {bt['n_cells']} cells.*\n")
    md.append("\n**Read this honestly:** a low or negative forward R² does NOT mean the "
              "model is broken — it means the engine does not predict the *absolute* future "
              "sales level (trend, seasonality and demand shocks dominate that). This is a "
              "price-**response** model, not a demand forecaster. Its real test is Section 2: "
              "when price actually moved, did volume respond as predicted?\n")

    md.append("\n## 2. Discount-move validation — the money claim\n")
    md.append("The core promise is *\"you can pull discount back without losing the volume we "
              "predict.\"* In the forward window the actual discount drifted on its own; did "
              "volume move the way the elasticity said?\n")
    if bt.get("move_table"):
        md.append("\n| Forward discount move | Cells | Predicted vol Δ | Actual vol Δ |")
        md.append("|---|---:|---:|---:|")
        for r in bt["move_table"]:
            md.append(f"| {r['move']} | {r['cells']} | {r['pred']:+.1f}% | {r['actual']:+.1f}% |")
    if bt.get("cut"):
        c = bt["cut"]
        md.append(f"\nOn the **{c['cells']} cells where discount actually fell** (price rose "
                  f"— the move the tool recommends), the engine predicted **{c['pred']:+.1f}%** "
                  f"volume and reality was **{c['actual']:+.1f}%**.\n")
    md.append("\n### Bottom line\n")
    md.append(f"- {bt['verdict_text']}\n")

    md.append("\n## What this proves\n")
    md.append("- The engine was trained blind to the validation window — a genuine forward "
              "test, the strongest evidence available before a brand acts live.\n")
    md.append("- It is not yet a *controlled* experiment (the forward moves were the brand's "
              "own, not randomised). A live price test, or the LIVE scoring in the weekly "
              "report's Track Record sheet, closes that last gap.\n")
    return md


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--weeks", type=int, default=8, help="forward holdout in weeks")
    args = ap.parse_args()

    print("=" * 72)
    print(f"  PROOF LOOP — out-of-time validation, {args.weeks}-week forward holdout")
    print("=" * 72)

    raw = ingest_all_sales()
    cal = load_event_calendar()
    _ = load_master_costs()
    fact = prepare_fact_table(raw, cal)
    feat = engineer_features(fact)

    bt = run_backtest(feat, weeks=args.weeks)

    out_dir = os.path.join(cfg.OUTPUT_DIR, "_proof_loop")
    os.makedirs(out_dir, exist_ok=True)
    md = _write_report(bt, out_dir, args.weeks)
    with open(os.path.join(out_dir, "PROOF_LOOP_REPORT.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    if bt.get("move_table"):
        pd.DataFrame(bt["move_table"]).to_csv(
            os.path.join(out_dir, "discount_move_validation.csv"), index=False)

    print("\n" + "=" * 72)
    if not bt.get("available"):
        print(f"  Backtest unavailable: {bt.get('reason')}")
        return
    print("  FORWARD FORECAST ACCURACY (holdout window the model never saw)")
    print("=" * 72)
    print(f"  Daily    R²={_n(bt['daily_r2'],3)}   MAPE={_n(bt['daily_mape'],1,'%')}")
    if bt.get("bin_r2") is not None:
        print(f"  3ppt-bin R²={_n(bt['bin_r2'],3)}   MAPE={_n(bt['bin_mape'],1,'%')}")
    if bt.get("move_table"):
        print("\n  DISCOUNT-MOVE VALIDATION (predicted vs actual volume change)")
        print("  " + pd.DataFrame(bt["move_table"]).to_string(index=False).replace("\n", "\n  "))
    print(f"\n  VERDICT: {bt['verdict_text']}")
    print(f"\n  Report: {os.path.join(out_dir, 'PROOF_LOOP_REPORT.md')}")


if __name__ == "__main__":
    main()
